version: "2.2"

services:
  pihole:
    container_name: locust
    image: timwebster9/locust
    ports:
      - "8089:8089"
    command: ["/usr/local/bin/locust", "-f", "/data/locustfile.py", "--host=http://springboot:4550"]
    restart: unless-stopped
  springboot:
    container_name: springboot
    image: timwebster9/springboot-template
    ports:
      - "4550:4550"
